services:
  backend:
    image: rtruong63/backend_quiz_app:latest
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/quiz_app
    depends_on:
      - mongo
    networks:
      - app_network
    restart: always

  frontend:
    image: rtruong63/frontend_quiz_app:latest
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
